### ISSUE TITLE
The G-buffer format depends on the render target format.

### ISSUE THREAD

**Issue by micklh** [nice-game/nice-game#11]
Currently the mesh batch code chooses an albedo channel format to match the final output format. We should instead choose a fixed format regardless of the final output format. We can minimize bandwidth by using a 24bpp sRGB format with three 8-bit channels, or we can improve color fidelity with a 32bpp sRGB format with three 10-bit channels. I'm not sure if Vulkan requires sRGB support on the 2:10:10:10 buffers, but even if it's completely unsupported, we can just render `sqrt(albedo)` to get the same benefits while still being very cheap to compress and then decompress in the next stage.

To clarify why: The albedo isn't actually a diffuse color value. It's the total percentage of light reflected by the material in the neighborhood of the texel. We'll need roughly the same amount of accuracy to produce good results no matter what color format we eventually tonemap down to.

**Comment by IcyDefiance** [comment]
Resolved by #12
